fs        = require 'fs'
shortcake = require '..'

option '-v', '--verbose', 'Verbose option'

task 'option', '', (options) ->
  console.log options.verbose

task 'task:options', '', (options) ->
  console.log options

task 'task:done', '', (done) ->
  console.log done
  done()

task 'task:options,done', '', (options, done) ->
  console.log options
  done()

task 'delay:0', '', ->
  console.log 'delay:0'

task 'delay:10', '', (done) ->
  setTimeout ->
    console.log 'delay:10'
    done()
  , 10

task 'delay:20', '', (options, done) ->
  setTimeout ->
    console.log 'delay:20'
    done()
  , 200

task 'invoke', '', ->
  invoke 'delay:20', ->
    invoke 'delay:10', ->
      invoke 'delay:0', ->
        console.log 'invoke'

task 'invoke.serial', '', ->
  invoke.serial ['delay:20', 'delay:10', 'delay:0'], ->
    console.log 'invoke.serial'

task 'invoke.parallel', '', ->
  invoke.parallel ['delay:20', 'delay:10', 'delay:0'], ->
    console.log 'invoke.parallel'

task 'gen', '', ->
  yield console.log 'gen-1'
  yield console.log 'gen-2'
  yield console.log 'gen-3'

task 'gen-promise', '', ->
  n = 0
  promise = ->
    new Promise (resolve, reject) ->
      n++
      setTimeout (-> resolve 'promise-' + n), 1000

  value = yield promise()
  console.log value

  value = yield promise()
  console.log value

  value = yield promise()
  console.log value
