require 'shortcake'
fs = require 'fs'

option '-v', '--verbose', 'Verbose option'

task 'async1', 'async task', (done) ->
  console.log 'async1'

  fs.readFile __filename, (err, data) ->
    done err, data

task 'async2', 'second async task', (options, done) ->
  console.log 'async2'

  fs.readFile __filename, (err, data) ->
    done err, data

task 'invoke:callback', 'call first then second task', ->
  invoke 'async1', ->
    invoke 'async2'
    console.log 'async3'

task 'invoke:serial', 'call first then second task', ->
  invoke ['async1', 'async2'], ->
    console.log 'async3'
